version: '3.7'

x-tm-amqp-config-variables: &tm-amqp-config
  TASK_MANAGER__RABBITMQ_HOST: rabbitmq

x-postgres-storage-config: &tm-postgres-storage-config
  TASK_MANAGER__BACKEND: amqp
  # Change this to a FSKeyValueStorageConfig if you don't want to use postgres
  TASK_MANAGER__STORAGE__HOST: postgres
  TASK_MANAGER__STORAGE__PORT: 5432
  TASK_MANAGER__STORAGE__PASSWORD: changeme

x-worker-config-variables: &worker-config
  ICIJ_WORKER_TYPE: amqp
  ICIJ_WORKER_RABBITMQ_HOST: rabbitmq
  ICIJ_WORKER_RABBITMQ_PORT: 5672

x-async-app-variables: &async-app
  EXTRACT_DATA_DIR: /usr/src/data
  EXTRACT_WORK_DIR: /usr/src/data/workdir
  EXTRACT_LOG_LEVEL: DEBUG


services:
  rabbitmq:
    image: rabbitmq:3.12.0-management
    container_name: extract-rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q status
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 5s
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres
    container_name: extract-postgres
    environment:
      POSTGRES_PASSWORD: changeme
    healthcheck:
      test: pg_isready
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 5s
    ports:
      - "5435:5432"

  http-service:
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    build:
      context: .
      target: http-service
    container_name: extract-http-service
    environment:
      <<: [ *tm-amqp-config, *tm-postgres-storage-config ]
      PORT: "8000"
      HOST: "0.0.0.0"
      LOG_LEVEL: DEBUG
      TASK_MANAGER__APP_PATH: extract_app
    healthcheck:
      test: curl -f http://localhost:8000/health
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 5s
    ports:
      - "8000:8000"

  extract-worker-cpu:
    depends_on:
      http-service:
        condition: service_healthy
    build:
      context: .
      args:
        dbmate_arch: $DBMATE_ARCH
      target: worker-cpu
    environment:
      <<: [ *worker-config, *async-app ]
    volumes:
      - type: bind
        source: ./data
        target: /usr/src/data

  extract-worker-miner-u:
    depends_on:
      http-service:
        condition: service_healthy
    build:
      context: .
      args:
        dbmate_arch: $DBMATE_ARCH
      target: worker-miner-u
    environment:
      <<: [ *worker-config, *async-app ]
    volumes:
      - type: bind
        source: ./data
        target: /usr/src/data
