name: Tests

on:
  push:
    branches: [ 'main' ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: format --check --config qa/ruff.toml
          version: 0.11.2
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.5"
          python-version: "3.11"
          enable-cache: true
      - name: Setup Python project
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install tesseract an
        run: | 
          sudo apt-get install -y tesseract-ocr \
              tesseract-ocr-eng \
              tesseract-ocr-fra \
              tesseract-ocr-deu \
              tesseract-ocr-spa \
              tesseract-ocr-lat \
              tesseract-ocr-jpn \
              libtesseract-dev \
              libleptonica-dev \
              pkg-config
          echo "TESSDATA_PREFIX=$(sudo dpkg -L tesseract-ocr-eng | grep tessdata$)" >> $GITHUB_ENV
      - name: Run tests
        run: uv run --dev --extra cpu --frozen pytest -vvv --cache-clear --show-capture=all -r A tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true